apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-gateway
  template:
    metadata:
      labels:
        app: sentiment-gateway
    spec:
      containers:
      - name: gateway
        image: edyarich/review-classification:v4
        resources:
          limits: # 128 Mi RAM, up to 1 vCPU
            memory: "128Mi"
            cpu: "1"
        env:
        - name: TF_SERVING_URL # URL the Flask app calls
          value: "http://sentiment-tf-serving:8501/v1/models/sentiment:predict"
        ports:
        - containerPort: 5000 # Flask listens here
