apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-gateway
  template:
    metadata:
      labels:
        app: sentiment-gateway
    spec:
      containers:
      - name: gateway
        image: edyarich/review-classification:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "2"
        env:
        - name: TF_SERVING_URL
          value: "http://sentiment-tf-serving:8501/v1/models/sentiment:predict"
        ports:
        - containerPort: 5000
