apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-tf-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-tf-serving
  template:
    metadata:
      labels:
        app: sentiment-tf-serving
    spec:
      containers:
      - name: tf-serving
        image: edyarich/sentiment-tf-serving:v3
        resources:
          limits: # 512 Mi RAM, up to 2 vCPU
            memory: "512Mi"
            cpu: "2"
        args:
          - --model_name=sentiment
          - --model_base_path=/models/sentiment
        ports:
          - containerPort: 8501
